name: pyqt_demo

on:
  push:
jobs:
  Packing:
    name: 打包发布-操作系统版本:(${{ matrix.os }},Python版本:${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"] # "ubuntu-18.04", "windows-latest","macos-latest"
        python-version: ["3.6"]
    steps:
      - name: 查看Windows环境
        run: |
          cd C:\Windows\SysWOW64
          ls -l
      - name: 下载代码
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Windows 准备Python3.6 X86 环境
        uses: actions/setup-python@v3
        with:
          python-version: 3.6.7
          architecture: x86
      - name: pip升级
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
      - name: Windows操作系统准备打包环境
        shell: bash
        run: |
          pip install -r requirements.txt
      - name: 编译打包
        env:
          PYTHONIOENCODING: "utf-8"
        shell: bash
        run: |
          python packing_app.py  # --specify_files samplesMain.py
      - name: 测试是否打包完成
        shell: bash
        run: |
          cd releases
          ls
      - uses: actions/upload-artifact@v3
        with:
          name: pyqt_demo
          path: |
            releases/

